  on:
    push:
      tags:
        - '*'
  jobs:
    tag_and_release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: rm -rf .git .DS_Store
        - run: mkdir /tmp/release
        - run: mv * /tmp/release
        - run: mv /tmp/release clue

        - uses: meeDamian/github-release@2.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            files: package:.
            gzip: true

